sudo: false
language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  # Ensure using latest pip, Travis provides wheels for most packages
  - pip install -U pip
  - pip install .
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - python setup.py nosetests --with-coverage
services:
  - mongodb
after_success:
  - codecov